services:
  app:
    build:
      context: ./conf/php
      dockerfile: Dockerfile
    image: laravel-todo-app
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres
      - node

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    command: sh -c "npm install && npm run build"
    # ↑ build のときだけ動くので常時起動ではない（これでOK）

  postgres:
    image: postgres:14.7-alpine3.17
    container_name: laravel_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passw@rd
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: passw@rd
    depends_on:
      - postgres
    ports:
      - "8888:80"

volumes:
  postgresql:
